my_list = []

my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)

print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])
print(my_list[4])
print(my_list[5])
print(my_list[6])
print(my_list[7])
print(my_list[8])
print(my_list[9])